// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHomeLibServer.Data;

#nullable disable

namespace MyHomeLibServer.Migrations
{
    [DbContext(typeof(LibDbContext))]
    [Migration("20220128224824_AddMappedFts")]
    partial class AddMappedFts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");
                });

            modelBuilder.Entity("AuthorSeries", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("AuthorSeries");
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.Author", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName", "MiddleName");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchiveFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeriesNo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Title");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.BooksFts", b =>
                {
                    b.Property<int>("RowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("books_fts");

                    b.Property<double?>("Rank")
                        .HasColumnType("REAL");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RowId");

                    b.ToTable("books_fts", (string)null);
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.Genre", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Keyword");
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.Series", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.SyncState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InpxFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("MyHomeLibServer.Data.Domain.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHomeLibServer.Data.Domain.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthorSeries", b =>
                {
                    b.HasOne("MyHomeLibServer.Data.Domain.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyHomeLibServer.Data.Domain.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.Book", b =>
                {
                    b.HasOne("MyHomeLibServer.Data.Domain.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.BooksFts", b =>
                {
                    b.HasOne("MyHomeLibServer.Data.Domain.Book", "Book")
                        .WithOne("FTS")
                        .HasForeignKey("MyHomeLibServer.Data.Domain.BooksFts", "RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.Genre", b =>
                {
                    b.HasOne("MyHomeLibServer.Data.Domain.Book", null)
                        .WithMany("Genres")
                        .HasForeignKey("BookId");
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.Keyword", b =>
                {
                    b.HasOne("MyHomeLibServer.Data.Domain.Book", null)
                        .WithMany("Keywords")
                        .HasForeignKey("BookId");
                });

            modelBuilder.Entity("MyHomeLibServer.Data.Domain.Book", b =>
                {
                    b.Navigation("FTS")
                        .IsRequired();

                    b.Navigation("Genres");

                    b.Navigation("Keywords");
                });
#pragma warning restore 612, 618
        }
    }
}
