---
kind: pipeline
type: exec
name: cloudflared

platform:
  os: linux

steps:
- name: Build docker
  commands:
  - docker build -t myhomelib -f MyHomeLibServer/Dockerfile .
- name: Run docker
  environment:
    COMPOSE_PROJECT_NAME: myhomelib
    LIBRARY:
      from_secret: LIBRARY
    INDEX:
      from_secret: INDEX
  commands:
  - docker-compose up -d
