services:
  torrserve:
    image: ghcr.io/yourok/torrserver:latest
    restart: unless-stopped
    ports:
      - "8090"
    volumes:
      - torrserve_data:/opt/torrserver

  myhomelib:
    build: .
    restart: unless-stopped
    ports:
      - "5080:8080"
    environment:
      Torrent__TorrServeUrl: http://torrserve:8090

      DOTNET_gcServer: 0
      DOTNET_GCHeapHardLimitPercent: 35
      DOTNET_GCConserveMemory: 9
      DOTNET_GCRetainVM: 0

volumes:
  torrserve_data:
